feat: add support for signature help
angular/vscode-ng-language-service pull request #1277
Opened 2021-04-12 19:17 UTC by alxhub

This commit adds support for signature help to the LS extension, by
translating from the TS `getSignatureHelpItems` API into LSP.

2021-04-12 20:35 UTC, zarend approved these changes
Looks good, but how come there are no tests? :)

2021-04-12 20:48 UTC, alxhub commented
I can't seem get the tests to pass on my machine. They fail even on `master`, with a fresh `node_modules`:

```
$ yarn test
yarn run v1.21.1
warning ng-template@12.0.0-next.0: The engine "vscode" appears to be invalid.
$ yarn compile:test && jasmine --config=jasmine.json
warning ng-template@12.0.0-next.0: The engine "vscode" appears to be invalid.
$ tsc -b server/src/tests && tsc -b client/src/tests
Randomized with seed 92707
Started
.........................F..........

Failures:
1) resolveAndRunNgcc runs ngcc from node_modules where ngcc is resolved to
  Message:
    Expected [object Promise] to be resolved.
  Stack:
    Error
        at <Jasmine>
        at UserContext.<anonymous> (/Users/arick/dev/vscode-ng-language-service/dist/server/tests/ngcc_spec.js:25:36)
        at <Jasmine>
        at processImmediate (internal/timers.js:439:21)
  Message:
    Expected 0 to be 1.
  Stack:
    Error: Expected 0 to be 1.
        at <Jasmine>
        at UserContext.<anonymous> (/Users/arick/dev/vscode-ng-language-service/dist/server/tests/ngcc_spec.js:26:35)
  Message:
    TypeError: Cannot destructure property `cwd` of 'undefined' or 'null'.
  Stack:
    TypeError: Cannot destructure property `cwd` of 'undefined' or 'null'.
        at UserContext.<anonymous> (/Users/arick/dev/vscode-ng-language-service/dist/server/tests/ngcc_spec.js:29:15)

36 specs, 1 failure
Finished in 0.043 seconds
```

So I want to add tests in a followup, after I talk to @kyliau and figure out what's up here.

2021-04-12 21:03 UTC, atscott requested changes
I think we should also add the client side short-circuit for this operation (ex: https://github.com/angular/vscode-ng-language-service/blob/master/client/src/client.ts#L67-L70)

2021-04-12 21:30 UTC, alxhub commented
> I think we should also add the client side short-circuit for this operation (ex: https://github.com/angular/vscode-ng-language-service/blob/master/client/src/client.ts#L67-L70)

Good call, done.

2021-04-12 21:32 UTC, alxhub commented
> So I want to add tests in a followup

I actually think this is necessary, since the framework LS PR hasn't landed yet. The feature can't actually work until that functionality is landed, released in an Angular version, and the extension is updated to depend on that version.

2021-04-12 21:40 UTC, atscott approved these changes

2021-04-12 21:56 UTC, alxhub commented
Per a conversation with @atscott, the practice for the extension repo is to open a PR with tests even if they're breaking, and only merge it once the feature PR lands upstream.

Tests are now added :)

2021-04-13 22:06 UTC, kyliau commented
blocked until 12.0.0-next.9 release

2021-04-15 15:15 UTC, merged