feat(language-service): Disable the rename provide in the built-in ex…
angular/vscode-ng-language-service pull request #1589
Opened 2022-01-12 15:31 UTC by ivanwonder

…tension of vscode

If the Angular LS starts before the built-in TS/JS extension,
the result is that renames will not work correctly from TS files
in the Angular project. The plugin in this PR will reject the
rename request for build-in TS/JS extension from vscode and the
vscode will ask the Angular LS to provide the rename info.

2022-01-12 15:35 UTC, ivanwonder commented
The plugin code move into this [PR](https://github.com/angular/angular/pull/44696)

2022-01-25 21:06 UTC, atscott commented
Adding the blocked label. This has to wait for the 13.2 release here since we don't yet have a branch for the next version that https://github.com/angular/angular/pull/44696 was included in.

2022-01-31 18:12 UTC, atscott requested changes
@ivanwonder LGTM aside from the commit message. Like the other commit, could you write it as the feature you're providing rather than the implementation details about how that was achieved?

That is: 
```
feat(extension): Support renaming from TypeScript files

<<details about how you did this. Disable rename provider of built in 
TS extension so VSCode asks the Angular Language Service for the answer instead. >>
```

2022-02-02 18:56 UTC, atscott approved these changes
🥳

2022-02-02 20:32 UTC, merged